on: [push]
env:
  DB_HOST : ${{ secrets.DB_HOST }}
  DB_USER : ${{ secrets.DB_USER }}
  DB_NAME : ${{ secrets.DB_NAME }}
  DB_PASSWORD : ${{ secrets.DB_PASSWORD }}
  DB_PORT : ${{ secrets.DB_PORT }}
  TEST_DB_NAME : ${{ secrets.TEST_DB_NAME }}
  DB_DIALECT:  ${{ secrets.DB_DIALECT }}
  PRIVATE_TOKEN_KEY: ${{ secrets.PRIVATE_TOKEN_KEY }}
  GH_ID : ${{ secrets.GH_ID }}  
  GH_SECRET : ${{ secrets_GH_SECRET }} 
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        cd server
        npm install
        npm run build --if-present
        npm run test --if-present=
